oaiCn:
  v1:
  - realm: 
      description: "Realm of oai"
      default: "openair4G.eur"
    snap:
      description: |
        Define the version of the snap to be used
      name: "oai-cn"
      channel: "edge"
      devmode: true
      refresh: false
    oaiHss:
      databaseServiceName: "mysql"
    oaiMme:
      mcc: "208"  
      mnc: "95"
    oaiSpgw:
      dns: "138.96.0.10"