version: '2'

services:
  oaicn: # Domain name of container
    image: mosaic5gecosys/oaicn:v1.1.0
    #restart: always # Operation Policy
    container_name: oaicn # Name of the container
    hostname: ubuntu # hostname
    privileged: true # Give the container the permission to manipulate the host
    depends_on: # Before starting this container, what should be ready
      - "mysql"
    volumes: # Mounted from host
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - ./conf.yaml:/root/config/conf.yaml:ro
    networks: # the network this container attached to
      - oai
  mysql:
    image: mysql:5.6
    #restart: always
    container_name: mysql
    environment: # shell variables
      - MYSQL_ROOT_PASSWORD=linux
    networks:
      - oai

networks: # Define our network here
  oai:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000 # Configure mtu
