oaiEnb:
- nodeFunction: "enbsim"
  mcc: "208"
  mnc: "95"
  mmeService:
    description: |
      If (ipv4) is provided, the enb connects to MME using the provied ip address. 
      Otherwise, it will connect to the service provided by (name)
      If both are provied, "ipv4" will be taked. If none of them is provided, the configuration will skip it and mme will not be configured
      snapVersion: the version of the snap, where the allowed versions are: "v1" and "v2"
    name: "oaicn"
    snapVersion: "v2"     # allowed values: v1, v2
    ipv4: ""
  # "flexRAN" and "flexRANServiceName" will be DEPRECATED, Please use "flexranService"
  flexRAN: false
  flexRANServiceName: "flexran"
  # flexranService:
  #   description: |
  #     If 'ipv4' and 'interfceName'are provided, the enb connects FlexRAN using the provied configuration.
  #     Otherwise, it will connect to the service FlexRAN provided by 'name'  
  #     If both are provied, 'ipv4' and  will be taked. If none of them is provided, the configuration will skip it and flexran will not be configured
  #     in the configuration file of oai-ran
  #   enabled: true
  #   name: "flexran"
  #   interface_name: ""
  #   ipv4: ""
  #   port: "2210"
  snap:
    description: |
      Define the version of the snap to be used. The field (refresh), if true, it will get the lates version of snap. 
      Otherwise, the current version (supposing that it is already installed) will be kept
    name: "oai-sim"
    channel: "edge"
    devmode: true
    refresh: false
    plugs: [network, network-control, log-observe, process-control, cpu-control, network-observe,
      network-bind, raw-usb, netlink-connector, hardware-observe]
  eutra_band:
    description: "Setting the LTE  EUTRA frequency band."
    default: "7"
  downlink_frequency:
    description: "Setting the downlink frequency band."
    default: "2685000000L"
  uplink_frequency_offset:
    description: "Setting the uplink frequency offset."
    default: "-120000000"
  N_RB_DL:
    description: "Setting the bandwidth in terms of number of available PRBS, 25 (5MHz),\
      \ 50 (10MHz), and 100 (20MHz)"
    default: "25"
  tx_gain:
    description: "transmission gain"
    default: "90"
  rx_gain:
    description: "reception gain"
    default: "125"
  pusch_p0_Nominal:
    description: ""
    default: "-96"
  pucch_p0_Nominal:
    description: ""
    default: "-104"
  pdsch_referenceSignalPower:
    description: ""
    default: "-27"
  puSch10xSnr:
    description: ""
    default: "200"
  puCch10xSnr:
    description: ""
    default: "200"
  parallel_config:
    description: |
      Defines the level of parallelism. There are three available values 
      PARALLEL_SINGLE_THREAD, PARALLEL_RU_L1_SPLIT, or PARALLEL_RU_L1_TRX_SPLIT
    default: "PARALLEL_SINGLE_THREAD"
  max_rxgain:
    description: "defines the maximum Rx gain"
    default: "110"
oaiCn:
  v2:
  - realm:
      description: "Realm of oai"
      default: "openair5G.eur"
    APN_NI:
      description: |
        APN of your network. Currently only one API is supported which will replace the default value of 
        the first api (oai.openair5G.eur) to the defined value
      default: "oai.ipv4"
    imsi:
      description: "List of IMSI to be added to the database with the defualt values of the other parameters like key, opc, etc."
      default: "226100000000001-226100000000003"
    # users: list of users to be added to the database if they do not have defualt values of the other parameters like key, opc, etc." 
    users:  >-
      [
          {
              "imsi": "226100000000001",
              "apn" : "oai.ipv4",
              "apn2" : "",
              "access_restriction" : 41, 
              "key" : "8baf473f2f8fd09487cccbd7097c6862", 
              "opc" : "8e27b6af0e692e750f32667a3b14605e", 
              "mmehost" : "ubuntu.openair5G.eur",
              "mmerealm" : "openair5G.com", 
              "msisdn" : 33663000021, 
              "rand" : "2683b376d1056746de3b254012908e0e", 
              "sqn" : 21,
              "static_ue_ipv4_allocation": "",
              "static_ue_ipv6_allocation": ""
          },
          {
              "imsi": "226100000000002",
              "apn" : "oai.ipv4",
              "apn2" : "",
              "access_restriction" : 41, 
              "key" : "8baf473f2f8fd09487cccbd7097c6862", 
              "opc" : "8e27b6af0e692e750f32667a3b14605e", 
              "mmehost" : "ubuntu.openair5G.eur", 
              "mmerealm" : "openair5G.com", 
              "msisdn" : 33663000021, 
              "rand" : "2683b376d1056746de3b254012908e0e", 
              "sqn" : 21,
              "static_ue_ipv4_allocation": "",
              "static_ue_ipv6_allocation": ""
          },
          {
              "imsi": "226100000000002",
              "apn" : "oai.ipv4",
              "apn2" : "",
              "access_restriction" : 41, 
              "key" : "8baf473f2f8fd09487cccbd7097c6862", 
              "opc" : "8e27b6af0e692e750f32667a3b14605e", 
              "mmehost" : "ubuntu.openair5G.eur", 
              "mmerealm" : "openair5G.com", 
              "msisdn" : 33663000021, 
              "rand" : "2683b376d1056746de3b254012908e0e", 
              "sqn" : 21,
              "static_ue_ipv4_allocation": "",
              "static_ue_ipv6_allocation": ""
          }
      ]
    oaiHss:
      snap:
        description: "snap of oai-hss"
        name: "oai-hss"
        channel: "edge"
        devmode: true
        refresh: false
        plugs: [home, network, desktop, mount-observe, process-control, network-control,
          network-observe, network-bind]
      databaseServiceName: "cassandra"
    oaiMme:
      snap:
        description: "snap of oai-mme"
        name: "oai-mme"
        channel: "edge"
        devmode: true
        refresh: false
        plugs: [mount-observe, system-backup, process-control, network-control, network-observe,
          network-bind, network]
      mcc: "208"
      mnc: "95"
    oaiSpgwc:
      snap:
        description: "snap of oai-spgwc"
        name: "oai-spgwc"
        channel: "edge"
        devmode: true
        refresh: false
        plugs: [log-observe, process-control, network-control, network-observe, network-bind]
      dns: "8.8.8.8"       # DNS of your network
    oaiSpgwu:
      snap:
        description: "snap of oai-spgwu"
        name: "oai-spgwu"
        channel: "edge"
        devmode: true
        refresh: false
        plugs: [log-observe, process-control, firewall-control, network-control, network-observe,
          network-bind]
