version: '2'

services:
  oaicn: # Domain name of container
    image: mosaic5gecosys/oaicn:v2.1.0
    restart: always # Operation Policy
    container_name: oaicn # Name of the container
    hostname: ubuntu # hostname
    privileged: true # Give the container the permission to manipulate the host
    depends_on: # Before starting this container, what should be ready
      - "cassandra"
    # cap_add:
    #   - SYS_ADMIN
    volumes: # Mounted from host
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - ./conf.yaml:/root/config/conf.yaml:ro
    networks: # the network this container attached to
      - oai
  oairan:
    image: mosaic5gecosys/oairan:v1.1.0
    restart: always
    container_name: oairan
    hostname: ubuntu
    privileged: true
    depends_on:
      - "cassandra"
      - "oaicn"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - /dev/bus/usb:/dev/bus/usb
      - ./conf.yaml:/root/config/conf.yaml:ro
    networks:
      - oai
  cassandra:
    image: mosaic5gecosys/cassandra-m5g:1.1
    restart: always
    container_name: cassandra
    hostname: ubuntu
    networks:
      - oai

networks: # Define our network here
  oai:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000 # Configure mtu
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.17.0.0/24
